"""
Extrapolation and Distance Plotting Module.

Generates a clean, square scatter plot analyzing how generalization error (RMSE) 
evolves with chemical distance, strictly using pre-computed metric DataFrames.
"""

import matplotlib.pyplot as plt
import pandas as pd
from typing import Tuple
from glass_dynamics.core.logger import logger

def plot_rmse_vs_distance_square(
    metrics_df: pd.DataFrame,
    figsize: Tuple[int, int] = (5, 5)
) -> plt.Figure:
    """
    Plots a square scatter plot of prediction RMSE vs. chemical distance.

    Parameters
    ----------
    metrics_df : pd.DataFrame
        DataFrame generated by the analysis module, containing 'Distance' and 'RMSE'.
    figsize : Tuple[int, int], default=(5, 5)
        Dimensions of the generated figure (kept equal to enforce square shape).

    Returns
    -------
    plt.Figure
        The rendered matplotlib figure.
    """
    logger.info("Rendering square scatter plot for Extrapolation Distance vs RMSE.")
    
    fig, ax = plt.subplots(figsize=figsize)
    
    # Force the plotting area to be a perfect square regardless of the data scale
    ax.set_box_aspect(1)

    # Plot baseline reference line
    ax.axhline(0.5, c='gray', alpha=0.5, ls='--', label='0.5 RMSE Baseline')
    
    # Scatter plot
    ax.plot(
        metrics_df['Distance'], 
        metrics_df['RMSE'], 
        marker='o', 
        ls='none', 
        markeredgecolor='black', 
        alpha=0.8, 
        color='steelblue'
    )

    # Formatting axes
    ax.set_xscale('log')
    ax.set_xlabel('Chemical Distance (Canberra)', fontsize=11)
    ax.set_ylabel('RMSE (Prediction vs Experimental)', fontsize=11)
    ax.set_title('Generalization Error vs. Distance', fontsize=12, fontweight='bold', pad=15)
    
    # Add a bit of padding so points don't clip the edges
    ax.margins(y=0.10, x=0.10)
    
    plt.tight_layout()

    return fig