"""
Top Features Evolution Visualization Module.

Generates clear, multi-panel line plots tracking the signed weights of the 
most important features. It explicitly highlights specific alpha values 
to allow easy cross-sectional comparison of feature stability.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from typing import Dict, Tuple, List
from glass_dynamics.core.logger import logger

def plot_top_features_evolution(
    evolution_dict: Dict[str, pd.DataFrame],
    highlight_alphas: List[float] = [1e-4, 1e-2, 0.1, 10.0],
    figsize: Tuple[int, int] = (16, 5)
) -> plt.Figure:
    """
    Plot the trajectory of the top features, highlighting specific alpha values.

    Parameters
    ----------
    evolution_dict : Dict[str, pd.DataFrame]
        Dictionary of DataFrames generated by the extraction module.
    highlight_alphas : List[float], default=[1e-4, 1e-2, 0.1, 10.0]
        Specific alpha values to highlight with vertical lines and markers.
    figsize : Tuple[int, int], default=(16, 5)
        Overall dimensions of the generated figure.

    Returns
    -------
    plt.Figure
        The rendered matplotlib figure.
    """
    target_names = list(evolution_dict.keys())
    n_targets = len(target_names)
    
    logger.info(f"Rendering evolution plots, highlighting {len(highlight_alphas)} alphas.")
    
    fig, axes = plt.subplots(1, n_targets, figsize=figsize, layout='constrained')
    if n_targets == 1:
        axes = [axes]
        
    for ax, target, panel_label in zip(axes, target_names, ['(a)', '(b)', '(c)']):
        df = evolution_dict[target]
        alphas = df.index.to_numpy()
        
        # Plot the continuous trajectories for each top feature
        for feature in df.columns:
            line, = ax.plot(alphas, df[feature], '-', linewidth=2, label=feature)
            
            # Extract exact values at the requested highlight alphas
            # We use np.interp or find the closest alpha in the array to place markers
            for h_alpha in highlight_alphas:
                # Find the closest alpha index in our spectrum
                closest_idx = (np.abs(alphas - h_alpha)).argmin()
                closest_alpha = alphas[closest_idx]
                val = df[feature].iloc[closest_idx]
                
                # Plot a clear marker exactly at the highlighted alpha
                ax.plot(closest_alpha, val, marker='o', color=line.get_color(), 
                        markersize=6, markeredgecolor='white', markeredgewidth=1)

        # Draw vertical reference lines for the highlighted alphas
        for h_alpha in highlight_alphas:
            ax.axvline(h_alpha, color='grey', linestyle=':', linewidth=1.5, alpha=0.7)
            
            # Add a small text label at the top of the line
            ax.text(h_alpha, ax.get_ylim()[1] * 0.95, f"$\\alpha$={h_alpha}", 
                    rotation=90, va='top', ha='right', fontsize=9, color='dimgrey')
            
        # Axes formatting
        ax.set_xscale('log')
        ax.set_xlabel(r'$\alpha$', fontsize=12)
        ax.set_ylabel(r'$w$', fontsize=12) if ax == axes[0] else ax.set_ylabel('')
        ax.set_title(f"Top Features Evolution: {target}", fontsize=13, fontweight='bold')
        
        # Horizontal baseline
        ax.axhline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)
        
        # Panel label
        ax.text(0.05, 0.92, panel_label, transform=ax.transAxes, fontsize=12)
        
        # Legend
        ax.legend(loc='best', frameon=True, fontsize=9, title="Top Features")

    return fig